services:
  speedcontrol-additions:
    image: speedcontrol-additions
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/opt/nodecg/bundles/speedcontrol-additions"
      - ./cfg:/opt/nodecg/cfg
      - ./db:/opt/nodecg/db
    ports:
      - "9090:9090"
